/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const GenerateUsernameLazyRouteImport = createFileRoute('/generate/$username')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const GenerateUsernameLazyRoute = GenerateUsernameLazyRouteImport.update({
  id: '/generate/$username',
  path: '/generate/$username',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/generate/$username.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/generate/$username': typeof GenerateUsernameLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/generate/$username': typeof GenerateUsernameLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/generate/$username': typeof GenerateUsernameLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate/$username'
  id: '__root__' | '/' | '/generate/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GenerateUsernameLazyRoute: typeof GenerateUsernameLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/$username': {
      id: '/generate/$username'
      path: '/generate/$username'
      fullPath: '/generate/$username'
      preLoaderRoute: typeof GenerateUsernameLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GenerateUsernameLazyRoute: GenerateUsernameLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
